---
title: Python核心编程之错误与异常
date: 2018-05-15 23:19:04
categories: Python
description: 按需求学习并记录Python各知识点，错误与异常处理好会让整个程序更加自动化。
tags:
 - Python
 - 异常处理
---

前面的话：最近在用Python进行数据分析，因此找到了《Python核心编程》一书学习。在设计自动化测试程序，常常因为数据各种异常导致测试程序停止，因此在代码中处理好这些异常就显得尤为重要。处理好异常可以防止程序自己终止，处理好异常并不表示异常就被解决，而是将让这些异常不影响整个程序运行。
### 错误与异常
错误可分为语法与逻辑：语法上错误即为不能被解释器或编译器编译，在程序执行前需要纠正；逻辑上的错误即为当语法正确后由于不完整或不合符的输入导致程序不能执行  
异常：当程序出现错误而在正常控制流以外出现的行为即错误发生的信号，当出现异常后当前流被打断，这种信号可以是解释器引发也可以由程序员引发。之后就是异常处理阶段。

### Python中的异常
通常错误都是由于和Python解释器不相容导致，后果即为引发异常。  
比如：NameError、SyntaxError、IndexError、KeyError、IOError等等。通常Python有一些自己检测和处理异常机制。

#### **try**
try语句：任何在该语句块内代码都会被检测有无异常发生。  
主要形式：try-except（可以有多个except子句）、try-finally（只能有一个finally）、try-except-finally复合语句
**try-except**语句

	try:                                 try:
    	try_suite  #监控这里的异常             f = open(file)
	except Exception[, reason]:          except IOError, e:
    	except_suite    # 处理异常代码        print('wrong open!')


如上实例：当file不存在时，不加try异常机制会引发编译器错误，而终止程序同时输出traceback信息。而当加上该机制会让程序即使对于try内语句没执行成功也能继续往下执行，同时打印出你自己能理解的信息(wrong open!)，此处可看出异常处理的好处。当file存在时，程序不会打印此消息而是继续往下执行。注意：当在上except中加入了IOError意味着机制只会捕捉这类异常，如果try内还存在其他异常需要手动加入这个异常。  
当异常发生后：若try内有多条语句，程序将不会执行发生点语句后的剩余语句，而编译器会搜索处理器(类似except下的print处理???)，若没找到异常会向上移交，上层重复搜索重复上移交，直到最顶层未被处理时，Python解释器会显示出跟踪返回信息，然后退出。

**多个except的try语句**
当你对try内的多条语句想要捕捉多个异常时，可以采用多个except处理。
形式有两种：

	try:						 		try:
    	try_suite							try_suite
    except Exception1[, reason1]:		except (Exception1, Exception2, ...)[, reason]:
    	except_suite_Exception1				except_suite
    except Exception2[,]reson2]
    	except_suite_Exception2

两种形式都可以，通常当考虑内存或设计方面要求所有异常必须使用同样的代码处理时，会采用第二种方式。第二种方式：可有无限的except，但是需要放在一个元祖内  
注意：不要在try块内放入一大片代码，try-except作用是提供一个可以提示错误或处理错误的机制，而不是过滤错误
* reason:是一个包含来自导致异常代码的诊断信息的类实例即一个Exception类的实例，在except_suite中传递参数给reason，用来提供更多异常的解释
* str(reason)：当在except_suite中使用str(reason)时，会返回一个良好可读的错误原因，类似调用类的__str__()方法。当第二种方式时，采用此方法可以看出到底是哪个异常
* else子句：try_except_else方式中，else语句表示当try范围内没有异常被检测到时，执行else中的子句
* finally子句：无论异常是否发生，是否会捕捉都会执行finally内的代码，从python2.5开始finnaly可以有try_except_finally或try_except_else_finally模式。

**try-finally语句**
该语句与try-except不同之处在于：该语句不是捕捉异常，而是维持一致的行为而无论异常是否发生。

	try:
    	try_suite
    finally:
    	finally_suite  #无论如何都会执行

当try内产生一个异常，会立即调到finally中finally_suite语句执行，当finally中所有代码执行完毕后，会继续向上一层引发异常。
常常被用于文件关闭行为，因为不管文件是否打开成功，都需要关闭文件对象。而最好不要在try-except中嵌套try-finally，因为会丢失一些信息

#### 上下文管理
**with语句**
在python2.6中正式启用with语句，用来简化代码。代替前面机制一些应用场景：文件（数据、日志、数据库等），线程资源，简单同步与数据库连接等。

	with context_expr [as var]:
    	with_suite

注意：该语句只能工作于支持上下文管理协议的对象即只有内建了”上下文管理“才能用with。比如{file、decimal.Context、thread.LockType、threading.Lock、threading.RLock、threading.Condition。。。。}

	with open(filePath, 'r') as f:
    	for eachLine in f:
        	# do stuff with eachLine 

with作用：利用with代开文件，它完成准备工作，当正常打开一个文件会把文件对象赋值给f，然后用迭代器遍历文件中每一行。当完成时，会关闭文件；当发生异常，也会执行清理操作，同时关闭文件。流程：
1. with与as间内容即上下文符号来获得一个上下文管理器，其职责为提供一个上下文对象，通过调用__context__()方法返回一个上下文对象
2. 当获得上下文对象，调用对象__enter()__方法完成with语句块执行前的所有准备工作，上中该方法会返回文件对象并利用as赋值给f'
3. 执行with语句块，当结束时不管正常还是异常都会调用上下文对象__exit()__
自对象上下文管理器：contextlib模块中函数用在你的函数或者对象上

### 触发异常
之前异常场景都是解释器引发即由于执行期间错误引发，当我们想自己在遇到错误的情况时手动触发异常时可用raise语句
**raise [SomeException [, args [, traceback]]]**
* 参数SomeExceptio: 触发异常的名字，必须是一个字符串、类或实例；其他参数必须在有第一参数时才能存在；
* args可选作为参数传递给异常，可以是一个单独对象也可以是元组，单个对象也要放入元组中才能传递即错误原因，多个元素元组通常是错误字符串与错误编号或者错误地址等
* traceback：可选，当异常被触发会新生成一个追踪对象
当参数是一个实例：若此实例不是异常类的实例，解释器会使用该实例的异常参数创建一个给定异常类的新实例；若是则会作为异常类子类出现  
raise后面也可以不跟任何参数：会引发当前代码块最近触发的一个异常，若之前没有异常触发将会生成一个TypeError异常  
raise、raise exclass、raise exclass()、raise exclass, args、raise exclass(args)、raise exclass,args,tb、raise string、...

### 断言
assert语句等价于布尔值判断，若表达式为假则发生异常，若断言成功则不采取任何措施，否者触发AssertionError断言错误异常
**assert expression [, arguments]**
注意AssertError异常和其他异常一样可以用try-except语句块捕捉，若没有捕捉程序还是会停止并提供traceback

	try:
    	assert 1 == 0, 'not eqqual'  #一个异常参数，此处可看成def assert(expr, args=None)
    except AssertError, args:
    	print('%s: %s')%(args.__class__.__name__, args)  # AssertionError: not equal

### 标准异常
标准异常集，所有异常都是内建，在脚本启动前或者交互命令提示符出现时已经可用了。  
BaseException 所有异常的基类		Exception 常规错误的基类		StandardError 所有内建标准异常基类 		Runtime 一般运行时的错  SyntaxError python语法错误		ReferenceError 弱引用视图访问已经垃圾回收了的对象	ValueError 对类型无效的操作
**创建异常**
需要继承标准异常类

	class MyException(Exception):
    	def __init__(self, *args):
        	self.args = args
	class loginError(MyException):
    	def __init__(self, code = 100, message = '异常登录', args = ('wrong',)):
        	self.args = args
            self.message = message
            self.code = code
	class loginoutError(MyException):
    	def __init__(self):
        	self.args = ('login out is wrong')
            self.message = 'wrong'
            self.code = 200
	try:
    	raise loginError()
    except loginError as e:
        print(e)
        print(e.code)
        print(e.message)

**异常和sys模块**
sys.exc_info()：提供了一个3元组（exc_type：异常类；exc_value：异常类的实例；exc_traceback：追踪对象）  
异常相关模块：exceptions 内建异常（永远不用导入这个模块） ceontextliba为使用with语句的上下文对象工具



